# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reminder_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("font: 12pt \"Comic Sans MS\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_workingh = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_workingh.setMaximumSize(QtCore.QSize(61, 30))
        self.comboBox_workingh.setObjectName("comboBox_workingh")
        self.gridLayout.addWidget(self.comboBox_workingh, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.comboBox_workingm = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_workingm.setMaximumSize(QtCore.QSize(61, 30))
        self.comboBox_workingm.setObjectName("comboBox_workingm")
        self.gridLayout.addWidget(self.comboBox_workingm, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_chillingh = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_chillingh.setMaximumSize(QtCore.QSize(61, 30))
        self.comboBox_chillingh.setObjectName("comboBox_chillingh")
        self.gridLayout.addWidget(self.comboBox_chillingh, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboBox_chillingm = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_chillingm.setMaximumSize(QtCore.QSize(61, 30))
        self.comboBox_chillingm.setObjectName("comboBox_chillingm")
        self.gridLayout.addWidget(self.comboBox_chillingm, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(361, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.button_begin = QtWidgets.QPushButton(self.frame_2)
        self.button_begin.setObjectName("button_begin")
        self.gridLayout_2.addWidget(self.button_begin, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.menuSettings.addAction(self.actionLanguage)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Working period:"))
        self.label_3.setText(_translate("MainWindow", "hour"))
        self.label_5.setText(_translate("MainWindow", "minutes"))
        self.label_2.setText(_translate("MainWindow", "Chilling period:"))
        self.label_4.setText(_translate("MainWindow", "hour"))
        self.label_6.setText(_translate("MainWindow", "minutes"))
        self.button_begin.setText(_translate("MainWindow", "Begin"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
